#ifndef TRADE_GLOBAL_H
#define TRADE_GLOBAL_H

#define TRADE_STATUS_NOTHING    0
#define TRADE_STATUS_BUYOPENED  1
#define TRADE_STATUS_SELLOPENED 2

#define TRADE_STATUS_OPENING     3
#define TRADE_STATUS_SELLCOLSING 4
#define TRADE_STATUS_BUYCLOSING  5
#define TRADE_STATUS_CANCELING   6

#define TRADE_ACTION_BUYOPEN   0
#define TRADE_ACTION_SELLOPEN  1
#define TRADE_ACTION_BUYCLOSE  2
#define TRADE_ACTION_SELLCLOSE 3
#define TRADE_ACTION_CANCEL    4

#endif
