#ifndef TRADE_GLOBAL_H
#define TRADE_GLOBAL_H

#define TRADE_STATUS_NOTHING    0
#define TRADE_STATUS_BUYOPENED  1
#define TRADE_STATUS_SELLOPENED 2

#define TRADE_STATUS_BUYOPENING  3
#define TRADE_STATUS_SELLOPENING 4
#define TRADE_STATUS_SELLCLOSING 5
#define TRADE_STATUS_BUYCLOSING  6

#define TRADE_STATUS_UNKOWN 7

#define TRADE_ACTION_BUYOPEN   0
#define TRADE_ACTION_SELLOPEN  1
#define TRADE_ACTION_BUYCLOSE  2
#define TRADE_ACTION_SELLCLOSE 3
#define TRADE_ACTION_CANCEL    4

#endif
